# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AsyncDisplayKitCollectionView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AsyncDisplayKit'
  # Pods for AsyncDisplayKitCollectionView

  target 'AsyncDisplayKitCollectionViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AsyncDisplayKitCollectionViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
