# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'QSDWebImageDemo' do
 pod 'SDWebImage', '~> 3.8.1'
end

target 'QSDWebImageDemoTests' do

end

target 'QSDWebImageDemoUITests' do

end

